#theme: jekyll-theme-minimal
title: holoLoveJK's homepage
description: "Capture The Flag writeups and notes"
baseurl: ""
url: "https://hololovejk.github.io"
theme: minima
paginate: 10
plugins:
  - jekyll-paginate
